apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::905646509583:user/github-WF
      username: github-WF
      groups:
        - system:masters