apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: ${AWS-IAM-USERARN}" 
      username: "${AWS-IAM-USERNAME}"
      groups:
        - system:masters
        - project