apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tech-execrise-v2
  region: us-east-2

nodeGroups:
  - name: tech-execrise-v2.1-nodes
    instanceName: tech-execrise-v2.1-nodes
    instanceType: t3.small
    desiredCapacity: 1
